services:
  postgres:
    image: postgres:17
    ports:
      - "3001:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_template
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
