apiVersion: 1

datasources:
  - name: Prometheus
    # plugin name
    type: prometheus
    # docker compose dns for now
    url: http://prometheus:9090
    isDefault: true
    # not editable through UI
    editable: false
