{
 "title": "Process Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Event Loop Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nodejs_eventloop_delay_p50_seconds * 1000",
     "legendFormat": "p50"
    },
    {
     "expr": "nodejs_eventloop_delay_p90_seconds * 1000",
     "legendFormat": "p90"
    },
    {
     "expr": "nodejs_eventloop_delay_p99_seconds * 1000",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Event Loop Delay Min/Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "nodejs_eventloop_delay_min_seconds * 1000",
     "legendFormat": "min"
    },
    {
     "expr": "nodejs_eventloop_delay_max_seconds * 1000",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "GC Minor/Incremental Duration - Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, v8js_gc_type) (rate(v8js_gc_duration_seconds_bucket{v8js_gc_type!=\"major\"}[5m]))) * 1000",
     "legendFormat": "{{v8js_gc_type}} p99"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, v8js_gc_type) (rate(v8js_gc_duration_seconds_bucket{v8js_gc_type!=\"major\"}[5m]))) * 1000",
     "legendFormat": "{{v8js_gc_type}} p50"
    }
   ]
  },
  {
   "title": "GC Major Duration - Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, v8js_gc_type) (rate(v8js_gc_duration_seconds_bucket{v8js_gc_type=\"major\"}[5m]))) * 1000",
     "legendFormat": "{{v8js_gc_type}} p99"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, v8js_gc_type) (rate(v8js_gc_duration_seconds_bucket{v8js_gc_type=\"major\"}[5m]))) * 1000",
     "legendFormat": "{{v8js_gc_type}} p50"
    }
   ]
  },
  {
   "title": "GC Count Rate",
   "type": "timeseries",
   "description": "How often GC runs per second on average during {range} minutes\n\n0.5 -> once every 2 seconds\n2.0 -> twice per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (v8js_gc_type) (\r\n  rate(v8js_gc_duration_seconds_count[1m])\r\n)",
     "legendFormat": "{{v8js_gc_type}}"
    }
   ]
  },
  {
   "title": "GC Duration %",
   "type": "timeseries",
   "description": "% of the time spent in GC, per type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(v8js_gc_type) (rate(v8js_gc_duration_seconds_sum[1m])) * 100",
     "legendFormat": "{{v8js_gc_type}}"
    }
   ]
  }
 ]
}