{
 "title": "Requests",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(\r\n  sum by (http_route, http_method) (\r\n    rate(http_server_duration_milliseconds_count{http_status_code=~\"[45]..\"}[1m])\r\n  )\r\n  or\r\n  sum by (http_route, http_method) (\r\n    rate(http_server_duration_milliseconds_count[1m]) * 0\r\n  )\r\n)\r\n/\r\nsum by (http_route, http_method) (\r\n  rate(http_server_duration_milliseconds_count[1m])\r\n) * 100",
     "legendFormat": "{{http_method}} {{http_route}} {{http_status_code}}"
    }
   ]
  },
  {
   "title": "Requests per Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (http_route, http_method) (\r\n  rate(http_server_duration_milliseconds_count[1m])\r\n) * 60",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Request Duration - Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, http_route, http_method) (rate(http_server_duration_milliseconds_bucket[5m])))",
     "legendFormat": "{{http_method}} {{http_route}} p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_route, http_method) (rate(http_server_duration_milliseconds_bucket[5m])))",
     "legendFormat": "{{http_method}} {{http_route}} p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, http_route, http_method) (rate(http_server_duration_milliseconds_bucket[5m])))",
     "legendFormat": "{{http_method}} {{http_route}} p50"
    }
   ]
  },
  {
   "title": "Avg Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (http_route, http_method) (rate(http_server_duration_milliseconds_sum[1m]))\r\n/\r\nsum by (http_route, http_method) (rate(http_server_duration_milliseconds_count[1m]))",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  }
 ]
}